# Generated by Django 3.1.4 on 2021-05-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biografi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descricion')),
                ('imag', models.ImageField(upload_to='Biografi', verbose_name='Imagen')),
                ('skills', models.CharField(max_length=30, verbose_name='Heramientas')),
                ('icon', models.ImageField(upload_to='', verbose_name='iconos')),
            ],
            options={
                'verbose_name': 'Biografia',
            },
        ),
    ]
