# Generated by Django 3.1.4 on 2021-05-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biografi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biografi',
            new_name='Bio',
        ),
    ]
