# Generated by Django 3.1.4 on 2021-05-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biografi', '0002_auto_20210519_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='icon1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='iconos 1'),
        ),
        migrations.AddField(
            model_name='bio',
            name='icon2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='iconos 2'),
        ),
        migrations.AddField(
            model_name='bio',
            name='icon3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='iconos 3'),
        ),
        migrations.AddField(
            model_name='bio',
            name='icon4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='iconos 4'),
        ),
        migrations.AddField(
            model_name='bio',
            name='icon5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='iconosb5'),
        ),
        migrations.AddField(
            model_name='bio',
            name='icon6',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='iconos 6'),
        ),
        migrations.AddField(
            model_name='bio',
            name='icon7',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='iconos 7'),
        ),
        migrations.AddField(
            model_name='bio',
            name='icon8',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='iconos 8'),
        ),
    ]
