# Generated by Django 3.1.4 on 2021-05-19 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biografi', '0003_auto_20210519_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='skills',
        ),
    ]
